// addSbtPlugin("com.github.gseitz"  % "sbt-release"     % "1.0.0")
// addSbtPlugin("com.jsuereth"       % "sbt-pgp"         % "1.0.0")
// addSbtPlugin("com.typesafe"       % "sbt-mima-plugin" % "0.1.14")
// addSbtPlugin("org.scala-js"       % "sbt-scalajs"     % "0.6.15")
// addSbtPlugin("org.tpolecat"       % "tut-plugin"      % "0.4.8")
// addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"    % "0.5.0")
// addSbtPlugin("pl.project13.scala" % "sbt-jmh"         % "0.1.15")
// addSbtPlugin("org.scoverage"      % "sbt-scoverage"   % "1.5.0")
