object TestGroups {

  val testGroups = List(
    Set("tests.RenameLspSuite", "tests.DebugProtocolSuite",
      "tests.debug.StackFrameDapSuite",
      "tests.worksheets.WorksheetNoDecorationsLspSuite",
      "tests.DidFocusLspSuite", "tests.remotels.RemoteLanguageServerLspSuite",
      "tests.MtagsSuite", "tests.FoldingRangeSuite",
      "tests.CreateDirectoriesSuite", "tests.DefinitionDirectorySuite",
      "tests.FilenameLength"),
    Set("tests.OnTypeFormattingSuite", "tests.RangeFormattingSuite",
      "tests.NewProjectLspSuite", "tests.WarningsLspSuite",
      "tests.QuickBuildSuite", "tests.DismissedNotificationsSuite",
      "tests.JdkSourcesSuite", "tests.DetectionSuite",
      "tests.BatchedFunctionSuite", "tests.InverseDependenciesSuite"),
    Set("tests.AmmoniteSuite", "tests.SyntaxErrorLspSuite",
      "tests.RelatedSuite", "tests.RangeFormattingWhenSelectingSuite",
      "tests.UnsupportedDebuggingLspSuite", "tests.FoldingRangeLspSuite",
      "tests.ChosenBuildToolSuite", "tests.UserConfigurationSuite",
      "tests.ScalaVersionsSuite", "tests.pants.PantsGlobsSuite",
      "tests.TimerSuite"),
    Set("tests.RangeFormattingWhenPastingSuite",
      "tests.codeactions.ImportMissingSymbolLspSuite", "tests.CascadeLspSuite",
      "tests.HoverLspSuite", "tests.FileWatcherLspSuite",
      "tests.WorkspaceSymbolExpectSuite", "tests.digest.MillDigestSuite",
      "tests.MtagsEnrichmentsSuite", "tests.debug.MessageIdAdapterSuite",
      "tests.CompressionSuite"),
    Set("tests.SuperMethodLspSuite", "tests.DefinitionLspSuite",
      "tests.WorkspaceSymbolLspSuite",
      "tests.codeactions.CreateNewSymbolLspSuite",
      "tests.CancelCompileLspSuite", "tests.DependencySourcesSuite",
      "tests.digest.MavenDigestSuite", "tests.NewFileTemplateSuite",
      "tests.MessagesSuite", "tests.TrigramSubstringsSuite"),
    Set("tests.ImplementationLspSuite", "tests.BillLspSuite",
      "tests.FormattingLspSuite", "tests.CompletionLspSuite",
      "tests.BuildServerConnectionLspSuite",
      "tests.WindowStateDidChangeLspSuite", "tests.ChosenBuildServerSuite",
      "tests.pants.PantsSuite", "tests.SbtOptsSuite", "tests.SuperMethodSuite",
      "tests.PrettyPrintTreeSuite"),
    Set("tests.ReferenceLspSuite", "tests.CodeLensesLspSuite",
      "tests.codeactions.ImplementAbstractMembersLspSuite",
      "tests.BspSwitchLspSuite", "tests.StatusBarLspSuite",
      "tests.JarTopLevelsSuite", "tests.digest.SbtDigestSuite",
      "tests.digest.PantsDigestSuite", "tests.SbtVersionSuite",
      "tests.pantsbuild.PantsProjectNameSuite"),
    Set("tests.debug.BreakpointDapSuite",
      "tests.codeactions.StringActionsLspSuite",
      "tests.DocumentHighlightLspSuite", "tests.AddPackageLspSuite",
      "tests.CompilersLspSuite", "tests.DefinitionSuite", "tests.ToplevelSuite",
      "tests.digest.GradleDigestSuite", "tests.HttpServerSuite",
      "tests.SelectBspServerSuite", "tests.FoldingRangesSuite"),
    Set("tests.ScalaToplevelSuite", "tests.debug.StepDapSuite",
      "tests.DiagnosticsLspSuite", "tests.SuperHierarchyLspSuite",
      "tests.CurrentProjectCompileLspSuite", "tests.digest.DigestsSuite",
      "tests.DocumentSymbolSuite", "tests.FuzzySuite",
      "tests.MetalsEnrichmentsSuite", "tests.OpenBrowserSuite"),
    Set("tests.worksheets.WorksheetLspSuite", "tests.CodeLensLspSuite",
      "tests.NewFilesLspSuite", "tests.TreeViewLspSuite",
      "tests.BuildTargetsLspSuite", "tests.DocumentSymbolLspSuite",
      "tests.SemanticdbSuite", "tests.JavadocSuite", "tests.LineListenerSuite",
      "tests.StatusBarSuite")
  )
}
