package scala.meta.internal.mtags

import java.io.UncheckedIOException
import java.nio.CharBuffer
import java.util.logging.Level
import java.util.logging.Logger

import scala.collection.mutable
import scala.util.Properties
import scala.util.control.NonFatal

import scala.meta.Dialect
import scala.meta.internal.io.FileIO
import scala.meta.internal.io.PathIO
import scala.meta.internal.io.PlatformFileIO
import scala.meta.internal.mtags.ScalametaCommonEnrichments._
import scala.meta.internal.semanticdb.Scala._
import scala.meta.internal.{semanticdb => s}
import scala.meta.io.AbsolutePath

final case class SymbolLocation(
    path: AbsolutePath,
    range: Option[s.Range]
)

/**
 * Index split on buckets per dialect in order to have a constant time
 * and low memory footprint to infer dialect for SymbolDefinition because
 * it's used in WorkspaceSymbolProvider
 *
 * @param toplevels keys are non-trivial toplevel symbols and values are the file
 *                  the symbols are defined in.
 * @param definitions keys are global symbols and the values are the files the symbols
 *                    are defined in. Difference between toplevels and definitions
 *                    is that toplevels contains only symbols generated by ScalaToplevelMtags
 *                    while definitions contains only symbols generated by ScalaMtags.
 */
class SymbolIndexBucket(
    toplevels: AtomicTrieMap[String, Set[AbsolutePath]],
    definitions: AtomicTrieMap[String, Set[SymbolLocation]],
    sourceJars: OpenClassLoader,
    toIndexSource: AbsolutePath => AbsolutePath = identity,
    mtags: Mtags,
    dialect: Dialect,
    onError: PartialFunction[Throwable, Unit]
) {

  private val logger = Logger.getLogger(classOf[SymbolIndexBucket].getName)

  private val maxParentResolutionDepth = 5

  /**
   * Indexing result of a single source file together with all its toplevel
   * symbols, including the "trivial" ones filtered out of
   * `IndexingResult.topLevels`.
   */
  private case class SourceIndex(
      result: IndexingResult,
      allToplevels: List[String],
      qualifiedParents: List[(String, List[String])]
  )

  def close(): Unit = sourceJars.close()

  def addSourceDirectory(
      dir: AbsolutePath
  ): List[IndexingResult] = {
    if (sourceJars.addEntry(dir.toNIO)) {
      dir.listRecursive.toList.flatMap {
        case source if source.isScala =>
          addSourceFile(source, Some(dir), isJava = false)
        case _ =>
          None
      }
    } else List.empty
  }

  def addSourceJar(
      jar: AbsolutePath,
      reindex: Boolean = false
  ): List[IndexingResult] = {
    if (reindex || sourceJars.addEntry(jar.toNIO)) {
      FileIO.withJarFileSystem(jar, create = false) { root =>
        try {
          val indexed = root.listRecursive.toList.flatMap {
            case source if source.isScala =>
              addSourceFileWithAllToplevels(source, None, isJava = false)
            case source if source.isJava =>
              addSourceFileWithAllToplevels(source, None, isJava = true)
            case _ =>
              None
          }
          enrichWithInheritedPackageObjectMembers(indexed)
        } catch {
          // this happens in broken jars since file from FileWalker should exists
          case _: UncheckedIOException => Nil
        }
      }
    } else
      List.empty
  }

  def addIndexedSourceJar(
      jar: AbsolutePath,
      symbols: List[(String, AbsolutePath)]
  ): Unit = {
    if (sourceJars.addEntry(jar.toNIO)) {
      symbols.foreach { case (sym, path) =>
        toplevels.updateWith(sym) {
          case Some(acc) => Some(acc + path)
          case None => Some(Set(path))
        }
      }
    }
    PlatformFileIO.newJarFileSystem(jar, create = false)
  }

  def addSourceFile(
      source: AbsolutePath,
      sourceDirectory: Option[AbsolutePath],
      isJava: Boolean
  ): Option[IndexingResult] =
    addSourceFileWithAllToplevels(source, sourceDirectory, isJava)
      .map(_.result)

  private def addSourceFileWithAllToplevels(
      source: AbsolutePath,
      sourceDirectory: Option[AbsolutePath],
      isJava: Boolean
  ): Option[SourceIndex] = try {
    val index = indexSource(source, dialect, sourceDirectory, isJava)
    index.result.topLevels.foreach { symbol =>
      toplevels.updateWith(symbol) {
        case Some(acc) => Some(acc + source)
        case None => Some(Set(source))
      }
    }
    Some(index)
  } catch {
    case NonFatal(e) =>
      onError(e)
      None
  }

  private def indexSource(
      source: AbsolutePath,
      dialect: Dialect,
      sourceDirectory: Option[AbsolutePath],
      isJava: Boolean
  ): SourceIndex = {
    val uri = source.toIdeallyRelativeURI(sourceDirectory)
    val (doc, overrides, toplevelMembers, qualifiedParents) =
      mtags.extendedIndexing(source, dialect)
    val sourceTopLevels =
      doc.occurrences.iterator
        .filterNot(_.symbol.isPackage)
        .map(_.symbol)
        .toList
    val topLevels =
      if (source.isScalaScript) sourceTopLevels
      else if (isJava) {
        sourceTopLevels.headOption
          .filter(sym => !isTrivialToplevelSymbol(uri, sym, "java"))
          .toList
      } else {
        sourceTopLevels
          .filter(sym => !isTrivialToplevelSymbol(uri, sym, "scala"))
      }
    SourceIndex(
      IndexingResult(source, topLevels, overrides, toplevelMembers),
      sourceTopLevels,
      qualifiedParents
    )
  }

  /**
   * Copies type members inherited through a package object's mixin parents
   * into its symbol space, so e.g. `import doobie.Transactor` is suggested for
   * an alias exposed via `package object doobie extends Aliases` (issue #2583).
   *
   * Each parent's full dotted path (kept separate from the simple-name
   * `overrides` channel used by the inheritance index) is resolved within the
   * same jar -- relative to the enclosing package, then absolute, then, for
   * unqualified names only, a unique simple-name match -- and otherwise skipped.
   * Resolution is transitive. Only type members are copied; term/module
   * re-exports (e.g. doobie's `val Transactor`) are a follow-up.
   */
  private def enrichWithInheritedPackageObjectMembers(
      indexed: List[SourceIndex]
  ): List[IndexingResult] = {
    val packageObjects = for {
      index <- indexed
      (symbol, parents) <- index.qualifiedParents
      if symbol.endsWith("/package.")
      if parents.nonEmpty
    } yield (symbol, parents)

    if (packageObjects.isEmpty) indexed.map(_.result)
    else {
      // Toplevel type symbols of the jar, before the trivial-symbol filter,
      // since parents like `com/foo/Aliases#` in `/com/foo/Aliases.scala`
      // are exactly the "trivial" ones.
      val definingFile = mutable.Map.empty[String, AbsolutePath]
      val byName = mutable.Map.empty[String, List[String]]
      for {
        index <- indexed
        symbol <- index.allToplevels
        if symbol.owner.isPackage
        if symbol.desc.isInstanceOf[Descriptor.Type]
        if !definingFile.contains(symbol)
      } {
        definingFile(symbol) = index.result.path
        val name = symbol.desc.name.value
        byName(name) = symbol :: byName.getOrElse(name, Nil)
      }

      // Resolves a parent written as a dotted path (e.g. `free.Types`) to a
      // toplevel type symbol defined in this jar. Tries the path relative to
      // the enclosing package first, then as an absolute path, and finally a
      // unique simple-name match anywhere in the jar.
      def resolveParent(
          enclosingOwner: String,
          path: String
      ): Option[String] = {
        val segments = path.split('.').toList
        def buildSymbol(prefix: String): String =
          segments.init.foldLeft(prefix)((acc, seg) => acc + seg + "/") +
            segments.last + "#"
        val relative = buildSymbol(enclosingOwner)
        if (definingFile.contains(relative)) Some(relative)
        else {
          val absolute = buildSymbol("")
          if (definingFile.contains(absolute)) Some(absolute)
          // Only an unqualified parent may fall back to a simple-name match. A
          // qualified parent that matches neither a relative nor an absolute
          // path is external, and must not be confused with an unrelated trait
          // of the same simple name that happens to live in the jar.
          else if (segments.lengthCompare(1) == 0)
            byName.getOrElse(segments.last, Nil) match {
              case unique :: Nil => Some(unique)
              case _ => None
            }
          else None
        }
      }

      val parsedWithMembers = mutable.Map
        .empty[
          AbsolutePath,
          (s.TextDocument, List[(String, List[String])])
        ]
      def indexWithMembers(path: AbsolutePath) =
        parsedWithMembers.getOrElseUpdate(
          path, {
            val (doc, _, _, qualifiedParents) =
              mtags.extendedIndexing(path, dialect, includeMembers = true)
            (doc, qualifiedParents)
          }
        )

      // (member name, definition range, defining file) of all type members
      // visible through `parentSymbol`, including transitively inherited ones.
      def typeMembersOf(
          parentSymbol: String,
          visited: Set[String],
          depth: Int
      ): List[(String, s.Range, AbsolutePath)] =
        if (depth > maxParentResolutionDepth || visited(parentSymbol)) Nil
        else
          definingFile.get(parentSymbol) match {
            case None => Nil
            case Some(path) =>
              val (doc, parentQualifiedParents) = indexWithMembers(path)
              val direct = doc.occurrences.iterator.collect {
                case occ
                    if occ.symbol.owner == parentSymbol &&
                      occ.symbol.desc.isInstanceOf[Descriptor.Type] =>
                  (
                    occ.symbol.desc.name.value,
                    occ.range.getOrElse(s.Range.defaultInstance),
                    path
                  )
              }.toList
              val transitive = for {
                (symbol, parents) <- parentQualifiedParents
                if symbol == parentSymbol
                parentPath <- parents
                resolved <- resolveParent(parentSymbol.owner, parentPath).toList
                member <- typeMembersOf(
                  resolved,
                  visited + parentSymbol,
                  depth + 1
                )
              } yield member
              direct ++ transitive
          }

      val seen = mutable.Set.empty[String]
      indexed.foreach { index =>
        index.result.toplevelMembers.foreach(member => seen += member.symbol)
      }
      val synthesized =
        mutable.Map.empty[AbsolutePath, mutable.ListBuffer[ToplevelMember]]
      for {
        (pkgObjSymbol, parentPaths) <- packageObjects
        parentPath <- parentPaths.distinct
        parent <- resolveParent(pkgObjSymbol.owner, parentPath).toList
        (memberName, range, path) <- typeMembersOf(parent, Set.empty, 0)
        memberSymbol = Symbols.Global(pkgObjSymbol, Descriptor.Type(memberName))
        // a member defined directly in the package object wins over an
        // inherited one, since it was already emitted with the same symbol
        if !seen(memberSymbol)
      } {
        seen += memberSymbol
        synthesized.getOrElseUpdate(path, mutable.ListBuffer.empty) +=
          ToplevelMember(memberSymbol, range, ToplevelMember.Kind.Type)
      }

      indexed.map { index =>
        synthesized.get(index.result.path) match {
          case Some(extra) =>
            index.result.copy(toplevelMembers =
              index.result.toplevelMembers ++ extra.toList
            )
          case None => index.result
        }
      }
    }
  }

  // Returns true if symbol is com/foo/Bar# and path is /com/foo/Bar.scala
  // Such symbols are "trivial" because their definition location can be computed
  // on the fly.
  private def isTrivialToplevelSymbol(
      path: String,
      symbol: String,
      extension: String = "scala"
  ): Boolean = {
    val pathBuffer =
      CharBuffer.wrap(path).subSequence(1, path.length - extension.length - 1)
    val symbolBuffer =
      CharBuffer.wrap(symbol).subSequence(0, symbol.length - 1)
    pathBuffer.equals(symbolBuffer)
  }

  def addToplevelSymbol(
      path: String,
      source: AbsolutePath,
      toplevel: String
  ): Unit = {
    if (source.isScalaScript || !isTrivialToplevelSymbol(path, toplevel)) {
      toplevels.updateWith(toplevel) {
        case Some(acc) => Some(acc + source)
        case None => Some(Set(source))
      }
    }
  }

  def findFileForToplevel(
      topLevelSymbol: Symbol
  ): List[(AbsolutePath, Dialect)] = {
    toplevels
      .get(topLevelSymbol.toString())
      .map(_.toList)
      .orElse(loadFromSourceJars(trivialPaths(topLevelSymbol)))
      .orElse(loadFromSourceJars(modulePaths(topLevelSymbol)))
      .getOrElse(Nil)
      .map(x => (x, dialect))
  }

  def query(symbol: Symbol): List[SymbolDefinition] =
    query0(symbol, symbol)

  /**
   * Returns the file where symbol is defined, if any.
   *
   * Uses two strategies to recover from missing symbol definitions:
   * - try to enter the toplevel symbol definition, then lookup symbol again.
   * - if the symbol is synthetic, for examples from a case class of macro annotation,
   *  fall back to related symbols from the enclosing class, see `DefinitionAlternatives`.
   *
   * @param querySymbol The original symbol that was queried by the user.
   * @param symbol The symbol that
   * @return
   */
  private def query0(
      querySymbol: Symbol,
      symbol: Symbol
  ): List[SymbolDefinition] = {

    removeOldEntries(symbol)

    if (!definitions.contains(symbol.value)) {
      // Fallback 1: enter the toplevel symbol definition
      val toplevel = symbol.toplevel
      val files = toplevels.get(toplevel.value)
      files match {
        case Some(files) =>
          files.foreach(addMtagsSourceFile(_))
        case _ =>
          loadFromSourceJars(trivialPaths(toplevel))
            .orElse(loadFromSourceJars(modulePaths(toplevel)))
            .foreach(_.foreach(addMtagsSourceFile(_)))
      }
      if (!definitions.contains(symbol.value)) {
        // Fallback 2: try with files for companion class
        if (toplevel.value.endsWith(".")) {
          val toplevelAlternative = s"${toplevel.value.stripSuffix(".")}#"
          for {
            companionClassFile <- toplevels
              .get(toplevelAlternative)
              .toSet
              .flatten
            if (!files.exists(_.contains(companionClassFile)))
          } addMtagsSourceFile(companionClassFile)
        }
      }
    }
    if (!definitions.contains(symbol.value)) {
      // Fallback 3: guess related symbols from the enclosing class.
      DefinitionAlternatives(symbol).flatMap(query0(querySymbol, _))
    } else {
      definitions
        .get(symbol.value)
        .map { paths =>
          paths.map { location =>
            SymbolDefinition(
              querySymbol = querySymbol,
              definitionSymbol = symbol,
              path = location.path,
              dialect = dialect,
              range = location.range,
              kind = None,
              properties = 0
            )
          }.toList
        }
        .getOrElse(List.empty)
    }
  }

  /**
   * Remove possible old, outdated entries from the toplevels and definitions.
   * This action is performed when a symbol is queried, to avoid returning incorrect results.
   */
  private def removeOldEntries(symbol: Symbol): Unit = {
    val exists =
      (toplevels.get(symbol.value).getOrElse(Set.empty) ++ definitions
        .get(symbol.value)
        .map(_.map(_.path))
        .getOrElse(Set.empty)).filter(_.exists)

    toplevels.updateWith(symbol.value) {
      case None => None
      case Some(acc) =>
        val updated = acc.filter(exists(_))
        if (updated.isEmpty) None
        else Some(updated)
    }

    definitions.updateWith(symbol.value) {
      case None => None
      case Some(acc) =>
        val updated = acc.filter(loc => exists(loc.path))
        if (updated.isEmpty) None
        else Some(updated)
    }
  }

  private def allSymbols(path: AbsolutePath): s.TextDocument = {
    val toIndexSource0 = toIndexSource(path)
    mtags.allSymbols(toIndexSource0, dialect)
  }

  // similar as addSourceFile except indexes all global symbols instead of
  // only non-trivial toplevel symbols.
  private def addMtagsSourceFile(
      file: AbsolutePath,
      retry: Boolean = true
  ): Unit = try {
    val docs: s.TextDocuments = PathIO.extension(file.toNIO) match {
      case "scala" | "java" | "sc" =>
        val document = allSymbols(file)
        s.TextDocuments(List(document))
      case _ =>
        s.TextDocuments(Nil)
    }
    if (docs.documents.nonEmpty) {
      addTextDocuments(file, docs)
    }
  } catch {
    case NonFatal(e) =>
      logger.log(Level.WARNING, s"Error indexing $file", e)
      if (retry) addMtagsSourceFile(file, retry = false)
  }

  // Records all global symbol definitions.
  private def addTextDocuments(
      file: AbsolutePath,
      docs: s.TextDocuments
  ): Unit = {
    docs.documents.foreach { document =>
      document.occurrences.foreach { occ =>
        if (occ.symbol.isGlobal && occ.role.isDefinition) {
          definitions.updateWith(occ.symbol) {
            case Some(acc) => Some(acc + SymbolLocation(file, occ.range))
            case None => Some(Set(SymbolLocation(file, occ.range)))
          }
        } else {
          // do nothing, we only care about global symbol definitions.
        }
      }
    }
  }

  // Returns the first path that resolves to a file.
  private def loadFromSourceJars(
      paths: List[String]
  ): Option[List[AbsolutePath]] = {
    paths match {
      case Nil => None
      case head :: tail =>
        sourceJars.resolveAll(head) match {
          case Nil => loadFromSourceJars(tail)
          case values => Some(values.map(AbsolutePath.apply))
        }
    }
  }

  // Returns relative file paths for trivial toplevel symbols, example:
  // Input:  scala/collection/immutable/List#
  // Output: scala/collection/immutable/List.scala
  //         scala/collection/immutable/List.java
  private def trivialPaths(toplevel: Symbol): List[String] = {
    val noExtension = toplevel.value.stripSuffix(".").stripSuffix("#")
    List(
      noExtension + ".scala",
      noExtension + ".java"
    )
  }

  private def modulePaths(toplevel: Symbol): List[String] = {
    if (Properties.isJavaAtLeast("9")) {
      val noExtension = toplevel.value.stripSuffix(".").stripSuffix("#")
      val javaSymbol = noExtension.replace("/", ".")
      for {
        cls <- sourceJars.loadClassSafe(javaSymbol).toList
        // note(@tgodzik) Modules are only available in Java 9+, so we need to invoke this reflectively
        module <- Option(
          cls.getClass().getMethod("getModule").invoke(cls)
        ).toList
        moduleName <- Option(
          module.getClass().getMethod("getName").invoke(module)
        ).toList
        file <- List(
          s"$moduleName/$noExtension.java",
          s"$moduleName/$noExtension.scala"
        )
      } yield file
    } else {
      Nil
    }
  }
}

object SymbolIndexBucket {

  def empty(
      dialect: Dialect,
      mtags: Mtags,
      toIndexSource: AbsolutePath => AbsolutePath,
      onError: PartialFunction[Throwable, Unit]
  ): SymbolIndexBucket =
    new SymbolIndexBucket(
      AtomicTrieMap.empty,
      AtomicTrieMap.empty,
      new OpenClassLoader,
      toIndexSource,
      mtags,
      dialect,
      onError
    )

}
