package scala.meta.internal.metals.mbt.importer

import scala.concurrent.ExecutionContext
import scala.concurrent.Future
import scala.util.Failure
import scala.util.Success
import scala.util.Try

import scala.meta.internal.metals.MetalsEnrichments._
import scala.meta.internal.metals.UserConfiguration
import scala.meta.internal.metals.mbt.MbtDependencyModule
import scala.meta.internal.process.ExitCodes
import scala.meta.internal.process.ProcessOutput
import scala.meta.internal.semver.SemVer
import scala.meta.io.AbsolutePath

object BazelScalaVersionResolver {
  // The `SCALA_VERSION='X.Y.Z'` line generated by rules_scala's `scala_config`.
  private val scalaConfigVersionPattern =
    """(?m)^\s*SCALA_VERSION\s*=\s*['"]([^'"]+)['"]""".r

  /**
   * The default Scala version from the `config.bzl` of rules_scala's generated
   * config repository, which `bazel query` materializes without a build.
   * Reading the resolved value works however the version was written in the
   * build files. `None` when the repository does not exist.
   */
  def scalaConfigVersion(configRepoDir: AbsolutePath): Option[String] = {
    val configBzl = configRepoDir.resolve("config.bzl")
    if (configBzl.isFile)
      Try(configBzl.readText).toOption
        .flatMap(scalaConfigVersionPattern.findFirstMatchIn)
        .map(_.group(1))
    else None
  }

  /**
   * The highest version of `scala-library` (Scala 2) or `scala3-library_3`
   * (Scala 3) among the dependency modules.
   */
  private def scalaVersionFromModules(
      modules: Seq[MbtDependencyModule]
  ): Option[String] = {
    val versions = modules.collect {
      case module
          if module.id.startsWith("org.scala-lang:scala-library:") ||
            module.id.startsWith("org.scala-lang:scala3-library_3:") =>
        module.id.split(":").last
    }
    maxVersion(versions)
  }

  /**
   * The workspace fallback Scala version, used for targets that declare no
   * `scala_version` of their own: rules_scala config repo > highest per-target
   * `scala_version` > stdlib module ids > user configuration.
   */
  def resolve(
      env: BazelQuery.Env,
      outputBase: Option[AbsolutePath],
      dependencyModules: Seq[MbtDependencyModule],
      scalaVersions: Map[String, List[String]],
      userConfiguration: UserConfiguration,
  )(implicit ec: ExecutionContext): Future[Option[String]] =
    queryScalaConfigRepo(env).map { scalaConfigRepo =>
      val scalaConfigRepoDir = for {
        base <- outputBase
        repo <- scalaConfigRepo
      } yield base.resolve("external").resolve(repo)
      scalaConfigRepoDir
        .flatMap(scalaConfigVersion)
        .orElse(maxVersion(scalaVersions.values.flatten))
        .orElse(scalaVersionFromModules(dependencyModules))
        .orElse(userConfiguration.fallbackScalaVersion)
    }

  /**
   * The canonical name of the rules_scala config repository used by the
   * current build. The name comes from the repository mapping:
   *  - WORKSPACE repositories are visible directly from the main repository
   *    when WORKSPACE is enabled alongside bzlmod,
   *  - otherwise the main repository maps to the rules_scala module, which maps
   *    to its config repository,
   *  - without bzlmod `bazel mod` fails, and the WORKSPACE name is used.
   */
  private def queryScalaConfigRepo(
      env: BazelQuery.Env
  )(implicit ec: ExecutionContext): Future[Option[String]] =
    queryRepoMapping(env, "").flatMap {
      case None => Future.successful(Some(workspaceScalaConfigRepo))
      case Some(mainMapping) =>
        mainMapping.get(workspaceScalaConfigRepo) match {
          case Some(workspaceRepo) => Future.successful(Some(workspaceRepo))
          case None =>
            List("rules_scala", "io_bazel_rules_scala")
              .flatMap(mainMapping.get)
              .headOption match {
              case Some(rulesScala) =>
                queryRepoMapping(env, rulesScala).map(
                  _.flatMap(_.get("rules_scala_config"))
                )
              case None => Future.successful(None)
            }
        }
    }

  private val workspaceScalaConfigRepo = "io_bazel_rules_scala_config"

  /** Apparent → canonical repository names visible from `repo`. */
  private def queryRepoMapping(env: BazelQuery.Env, repo: String)(implicit
      ec: ExecutionContext
  ): Future[Option[Map[String, String]]] = {
    val buf = new StringBuilder()
    env.shellRunner
      .run(
        "bazel-mod-dump-repo-mapping",
        List("bazel", "mod", "dump_repo_mapping", repo),
        env.projectRoot,
        redirectErrorOutput = false,
        javaHome = env.javaHome,
        processOut = ProcessOutput.Lines(line => buf.append(line)),
        processErr = _ => (),
      )
      .future
      .map {
        case ExitCodes.Success =>
          Try(
            ujson
              .read(buf.toString)
              .obj
              .map { case (apparent, canonical) =>
                apparent -> canonical.str
              }
              .toMap
          ).toOption
        case _ => None
      }
  }

  /** The highest of `versions` that parses as a Scala/SemVer version. */
  def maxVersion(versions: Iterable[String]): Option[String] =
    versions.toSeq.distinct
      .flatMap { version =>
        Try(SemVer.Version.fromString(version)) match {
          case Success(parsed) => Some(version -> parsed)
          case Failure(_) =>
            scribe.error(
              s"bazel-mbt: could not parse Scala version '$version'; ignoring it"
            )
            None
        }
      }
      .maxByOption { case (_, parsed) => parsed }
      .map { case (version, _) => version }
}
