package scala.meta.internal.metals.mbt.importer

import java.nio.file.Files
import java.nio.file.Path

import scala.util.Failure
import scala.util.Success
import scala.util.Try
import scala.util.Using

import scala.meta.internal.metals.MetalsEnrichments._
import scala.meta.internal.metals.UserConfiguration
import scala.meta.internal.metals.mbt.MbtDependencyModule
import scala.meta.internal.semver.SemVer
import scala.meta.io.AbsolutePath

object BazelScalaVersionResolver {

  // The `SCALA_VERSION='X.Y.Z'` line generated by rules_scala's `scala_config`.
  private val scalaConfigVersionPattern =
    """(?m)^\s*SCALA_VERSION\s*=\s*['"]([^'"]+)['"]""".r

  /**
   * The default Scala version from the generated `@…rules_scala_config`
   * repository's `config.bzl`, which `bazel query` materializes without a
   * build. Reading the resolved value works however the version was written in
   * the build files. Stale repositories may linger after a rename, so the
   * most recently written one wins. `None` when rules_scala is not in use.
   */
  def scalaConfigVersion(externalDir: Path): Option[String] = {
    val versionsByModifiedTime = for {
      dir <- listDirectory(externalDir)
      if dir.getFileName.toString.endsWith("rules_scala_config")
      configBzl = dir.resolve("config.bzl")
      if Files.isRegularFile(configBzl)
      modified <- Try(Files.getLastModifiedTime(configBzl).toMillis).toOption
      content <- Try(new String(Files.readAllBytes(configBzl))).toOption
      matched <- scalaConfigVersionPattern.findFirstMatchIn(content)
    } yield modified -> matched.group(1)
    versionsByModifiedTime
      .maxByOption { case (modified, _) => modified }
      .map { case (_, version) => version }
  }

  private def listDirectory(dir: Path): List[Path] =
    if (Files.isDirectory(dir))
      Using(Files.list(dir))(_.iterator().asScala.toList).fold(
        error => {
          scribe.warn(s"bazel-mbt: could not list $dir: ${error.getMessage}")
          Nil
        },
        identity,
      )
    else Nil

  /**
   * The highest version of `scala-library` (Scala 2) or `scala3-library_3`
   * (Scala 3) among the dependency modules.
   */
  private def scalaVersionFromModules(
      modules: Seq[MbtDependencyModule]
  ): Option[String] = {
    val versions = modules.collect {
      case module
          if module.id.startsWith("org.scala-lang:scala-library:") ||
            module.id.startsWith("org.scala-lang:scala3-library_3:") =>
        module.id.split(":").last
    }
    maxVersion(versions)
  }

  /**
   * The workspace fallback Scala version, used for targets that declare no
   * `scala_version` of their own: rules_scala config repo > highest per-target
   * `scala_version` > stdlib module ids > user configuration.
   */
  def resolve(
      outputBase: Option[AbsolutePath],
      dependencyModules: Seq[MbtDependencyModule],
      scalaVersions: Map[String, List[String]],
      userConfiguration: UserConfiguration,
  ): Option[String] =
    outputBase
      .flatMap(base => scalaConfigVersion(base.resolve("external").toNIO))
      .orElse(maxVersion(scalaVersions.values.flatten))
      .orElse(scalaVersionFromModules(dependencyModules))
      .orElse(userConfiguration.fallbackScalaVersion)

  /** The highest of `versions` that parses as a Scala/SemVer version. */
  def maxVersion(versions: Iterable[String]): Option[String] =
    versions.toSeq.distinct
      .flatMap { version =>
        Try(SemVer.Version.fromString(version)) match {
          case Success(parsed) => Some(version -> parsed)
          case Failure(_) =>
            scribe.error(
              s"bazel-mbt: could not parse Scala version '$version'; ignoring it"
            )
            None
        }
      }
      .maxByOption { case (_, parsed) => parsed }
      .map { case (version, _) => version }
}
