package scala.meta.internal.builds.bazelnative

import java.nio.charset.StandardCharsets
import java.nio.file.Files

import scala.meta.internal.metals.Directories
import scala.meta.io.AbsolutePath

/**
 * Materializes a Bazel aspect into the workspace and provides the CLI
 * flags that attach it to `bazel build` invocations.
 *
 * The aspect collects build metadata (sources, deps, compiler options,
 * output JARs, toolchain info, …) and writes one JSON file per target.
 * These files are then parsed by [[BazelNativeTargetInfoReader]].
 */
class BazelNativeAspectsManager(workspace: AbsolutePath) {

  private val aspectDir: AbsolutePath =
    workspace.resolve(Directories.bazelNative).resolve("aspects")

  private val bzlFile: AbsolutePath =
    aspectDir.resolve("bsp_target_info.bzl")

  private val buildFile: AbsolutePath =
    aspectDir.resolve("BUILD")

  @volatile private var _bazelMajor: Int = 0

  /** Write aspect files to disk.  Idempotent. */
  def materialize(
      scalaRulesetName: Option[String],
      bazelVersion: String = "",
  ): Unit = {
    _bazelMajor = bazelMajorVersion(bazelVersion)
    Files.createDirectories(aspectDir.toNIO)
    val content = aspectBzlContent(scalaRulesetName)
    Files.write(bzlFile.toNIO, content.getBytes(StandardCharsets.UTF_8))
    if (!buildFile.isFile)
      Files.write(buildFile.toNIO, Array.emptyByteArray)
    materializeSemanticdbToolchain(scalaRulesetName)
  }

  /**
   * If MODULE.bazel registers a `//:semanticdb_toolchain` but the root
   * BUILD file doesn't define it, append the necessary targets so that
   * toolchain resolution doesn't fail.
   */
  private def materializeSemanticdbToolchain(
      scalaRulesetName: Option[String]
  ): Unit = {
    val moduleBazel = workspace.resolve("MODULE.bazel")
    if (!moduleBazel.isFile) return

    val moduleContent = new String(
      Files.readAllBytes(moduleBazel.toNIO),
      StandardCharsets.UTF_8,
    )
    if (!moduleContent.contains("register_toolchains"))
      return

    val toolchainLabelPattern =
      """register_toolchains\(\s*"(//:(\w+))"\s*\)""".r
    val toolchainMatch =
      toolchainLabelPattern.findFirstMatchIn(moduleContent)
    if (toolchainMatch.isEmpty) return
    val toolchainName = toolchainMatch.get.group(2)

    val rootBuild = workspace.resolve("BUILD")
    val rootBuildBazel = workspace.resolve("BUILD.bazel")
    val buildPath =
      if (rootBuildBazel.isFile) rootBuildBazel
      else if (rootBuild.isFile) rootBuild
      else return

    val buildContent = new String(
      Files.readAllBytes(buildPath.toNIO),
      StandardCharsets.UTF_8,
    )
    if (buildContent.contains(s""""$toolchainName""""))
      return

    val rulesetPath = scalaRulesetName.getOrElse("rules_scala")
    val implName = toolchainName + "_impl"
    val stanza =
      s"""|
          |# Auto-generated by Metals for SemanticDB support.
          |load("@$rulesetPath//scala:scala_toolchain.bzl", "scala_toolchain")
          |
          |scala_toolchain(
          |    name = "$implName",
          |    enable_semanticdb = True,
          |    semanticdb_bundle_in_jar = False,
          |    visibility = ["//visibility:public"],
          |)
          |
          |toolchain(
          |    name = "$toolchainName",
          |    toolchain = "$implName",
          |    toolchain_type = "@$rulesetPath//scala:toolchain_type",
          |    visibility = ["//visibility:public"],
          |)
          |""".stripMargin

    Files.write(
      buildPath.toNIO,
      (buildContent + stanza).getBytes(StandardCharsets.UTF_8),
    )
    scribe.info(
      s"[BazelNative BSP] Appended semanticdb toolchain to ${buildPath.toNIO.getFileName}"
    )
  }

  def aspectsFlag: String =
    s"//${Directories.bazelNative}/aspects:bsp_target_info.bzl%bsp_target_info_aspect"

  def outputGroupsSyncFlag: String = "bsp-target-info"
  def outputGroupsCompileFlag: String = "+bsp-target-info"

  def extraSyncFlags: List[String] = List(
    s"--aspects=$aspectsFlag",
    s"--output_groups=$outputGroupsSyncFlag",
    "--keep_going",
    "--curses=no",
  )

  def extraCompileFlags: List[String] = List(
    s"--aspects=$aspectsFlag",
    s"--output_groups=$outputGroupsCompileFlag",
  )

  def detectScalaRulesetName(): Option[String] = {
    val candidates = List("MODULE.bazel", "WORKSPACE", "WORKSPACE.bazel")
    candidates.iterator
      .map(workspace.resolve)
      .filter(_.isFile)
      .flatMap { file =>
        val content = new String(
          Files.readAllBytes(file.toNIO),
          StandardCharsets.UTF_8,
        )
        if (content.contains("io_bazel_rules_scala"))
          Some("io_bazel_rules_scala")
        else if (content.contains("rules_scala")) Some("rules_scala")
        else None
      }
      .nextOption()
  }

  private def bazelMajorVersion(bazelVersion: String): Int = {
    if (bazelVersion.isEmpty) return 0
    try bazelVersion.takeWhile(_.isDigit).toInt
    catch { case _: NumberFormatException => 0 }
  }

  private val TemplateResource = "bazelnative/bsp_target_info.bzl.template"

  private def aspectBzlContent(scalaRulesetName: Option[String]): String = {
    val scalaToolchainType = scalaRulesetName match {
      case Some(name) => s""""@$name//scala:toolchain_type""""
      case None => "None"
    }

    val javaInfoLoad =
      if (_bazelMajor >= 8)
        """load("@@rules_java+//java/common:java_info.bzl", "JavaInfo")"""
      else ""

    val template = {
      val stream = getClass.getClassLoader.getResourceAsStream(TemplateResource)
      if (stream == null)
        throw new IllegalStateException(
          s"Missing classpath resource: $TemplateResource"
        )
      try new String(stream.readAllBytes(), StandardCharsets.UTF_8)
      finally stream.close()
    }

    template
      .replace("{{JAVA_INFO_LOAD}}", javaInfoLoad)
      .replace("{{SCALA_TOOLCHAIN_TYPE}}", scalaToolchainType)
  }
}
