package scala.meta.internal.builds.bazelnative

import java.nio.charset.StandardCharsets
import java.nio.file.Files

import scala.meta.io.AbsolutePath

/**
 * Materializes a Bazel aspect into the workspace and provides the CLI
 * flags that attach it to `bazel build` invocations.
 *
 * The aspect collects build metadata (sources, deps, compiler options,
 * output JARs, toolchain info, …) and writes one JSON file per target.
 * These files are then parsed by [[BazelNativeTargetInfoReader]].
 */
class BazelNativeAspectsManager(workspace: AbsolutePath) {

  private val aspectDir: AbsolutePath =
    workspace.resolve(".metals-bsp").resolve("aspects")

  private val bzlFile: AbsolutePath =
    aspectDir.resolve("bsp_target_info.bzl")

  private val buildFile: AbsolutePath =
    aspectDir.resolve("BUILD")

  @volatile private var _bazelMajor: Int = 0

  /** Write aspect files to disk.  Idempotent. */
  def materialize(
      scalaRulesetName: Option[String],
      bazelVersion: String = "",
  ): Unit = {
    _bazelMajor = bazelMajorVersion(bazelVersion)
    Files.createDirectories(aspectDir.toNIO)
    val content = aspectBzlContent(scalaRulesetName)
    Files.write(bzlFile.toNIO, content.getBytes(StandardCharsets.UTF_8))
    if (!buildFile.isFile)
      Files.write(buildFile.toNIO, Array.emptyByteArray)
    materializeSemanticdbToolchain(scalaRulesetName)
  }

  /**
   * If MODULE.bazel registers a `//:semanticdb_toolchain` but the root
   * BUILD file doesn't define it, append the necessary targets so that
   * toolchain resolution doesn't fail.
   */
  private def materializeSemanticdbToolchain(
      scalaRulesetName: Option[String]
  ): Unit = {
    val moduleBazel = workspace.resolve("MODULE.bazel")
    if (!moduleBazel.isFile) return

    val moduleContent = new String(
      Files.readAllBytes(moduleBazel.toNIO),
      StandardCharsets.UTF_8,
    )
    if (!moduleContent.contains("register_toolchains"))
      return

    val toolchainLabelPattern =
      """register_toolchains\(\s*"(//:([\w-]+))"\s*\)""".r
    val toolchainMatch =
      toolchainLabelPattern.findFirstMatchIn(moduleContent)
    if (toolchainMatch.isEmpty) return
    val toolchainName = toolchainMatch.get.group(2)

    val rootBuild = workspace.resolve("BUILD")
    val rootBuildBazel = workspace.resolve("BUILD.bazel")
    val buildPath =
      if (rootBuildBazel.isFile) rootBuildBazel
      else if (rootBuild.isFile) rootBuild
      else return

    val buildContent = new String(
      Files.readAllBytes(buildPath.toNIO),
      StandardCharsets.UTF_8,
    )
    if (buildContent.contains(s""""$toolchainName""""))
      return

    val rulesetPath = scalaRulesetName.getOrElse("rules_scala")
    val implName = toolchainName + "_impl"
    val stanza =
      s"""|
          |# Auto-generated by Metals for SemanticDB support.
          |load("@$rulesetPath//scala:scala_toolchain.bzl", "scala_toolchain")
          |
          |scala_toolchain(
          |    name = "$implName",
          |    enable_semanticdb = True,
          |    semanticdb_bundle_in_jar = False,
          |    visibility = ["//visibility:public"],
          |)
          |
          |toolchain(
          |    name = "$toolchainName",
          |    toolchain = "$implName",
          |    toolchain_type = "@$rulesetPath//scala:toolchain_type",
          |    visibility = ["//visibility:public"],
          |)
          |""".stripMargin

    Files.write(
      buildPath.toNIO,
      (buildContent + stanza).getBytes(StandardCharsets.UTF_8),
    )
    scribe.info(
      s"[BazelNative BSP] Appended semanticdb toolchain to ${buildPath.toNIO.getFileName}"
    )
  }

  /** `--aspects` flag value. */
  def aspectsFlag: String =
    s"//.metals-bsp/aspects:bsp_target_info.bzl%bsp_target_info_aspect"

  /** `--output_groups` flag for sync (replace default groups). */
  def outputGroupsSyncFlag: String = "bsp-target-info"

  /** `--output_groups` flag for compile (add to default groups). */
  def outputGroupsCompileFlag: String = "+bsp-target-info"

  private def autoloadFlags: List[String] = Nil

  def extraSyncFlags: List[String] = List(
    s"--aspects=$aspectsFlag",
    s"--output_groups=$outputGroupsSyncFlag",
    "--keep_going",
    "--curses=no",
  ) ++ autoloadFlags

  def extraCompileFlags: List[String] = List(
    s"--aspects=$aspectsFlag",
    s"--output_groups=$outputGroupsCompileFlag",
  ) ++ autoloadFlags

  /** Detect the rules_scala apparent repo name from workspace files. */
  def detectScalaRulesetName(): Option[String] = {
    val candidates = List("MODULE.bazel", "WORKSPACE", "WORKSPACE.bazel")
    candidates.iterator
      .map(workspace.resolve)
      .filter(_.isFile)
      .flatMap { file =>
        val content = new String(
          Files.readAllBytes(file.toNIO),
          StandardCharsets.UTF_8,
        )
        if (content.contains("io_bazel_rules_scala"))
          Some("io_bazel_rules_scala")
        else if (content.contains("rules_scala")) Some("rules_scala")
        else None
      }
      .nextOption()
  }

  // ---------------------------------------------------------------------------
  // Starlark aspect source
  // ---------------------------------------------------------------------------

  private def bazelMajorVersion(bazelVersion: String): Int = {
    if (bazelVersion.isEmpty) return 0
    try bazelVersion.takeWhile(_.isDigit).toInt
    catch { case _: NumberFormatException => 0 }
  }

  private def aspectBzlContent(scalaRulesetName: Option[String]): String = {
    val scalaToolchainType = scalaRulesetName match {
      case Some(name) => s""""@$name//scala:toolchain_type""""
      case None => "None"
    }

    val javaInfoLoad =
      if (_bazelMajor >= 8)
        """load("@@rules_java+//java/common:java_info.bzl", "JavaInfo")
          |""".stripMargin
      else ""

    s"""# Generated by Metals – do not edit.
       |${javaInfoLoad}
       |BspInfo = provider(fields = [
       |    "id", "output_groups", "java_toolchain_info", "java_runtime_info",
       |])
       |
       |COMPILE = 0
       |RUNTIME = 1
       |
       |def _abs(n):
       |    return -n if n < 0 else n
       |
       |def _file_loc(f):
       |    if f == None:
       |        return None
       |    return struct(
       |        path = f.path,
       |        short_path = f.short_path,
       |        is_source = f.is_source,
       |    )
       |
       |def _file_locs(files):
       |    return [_file_loc(f) for f in files if f != None]
       |
       |def _files_from_attr(attr):
       |    result = []
       |    if type(attr) == "list":
       |        for t in attr:
       |            if hasattr(t, "files"):
       |                result.extend(t.files.to_list())
       |    return result
       |
       |def _collect_targets(rule_attrs, attr_names):
       |    result = []
       |    for name in attr_names:
       |        if not hasattr(rule_attrs, name):
       |            continue
       |        val = getattr(rule_attrs, name)
       |        if type(val) == "Target":
       |            if BspInfo in val:
       |                result.append(val)
       |        elif type(val) == "list":
       |            for t in val:
       |                if type(t) == "Target" and BspInfo in t:
       |                    result.append(t)
       |    return result
       |
       |def _merge_output_groups(groups, deps):
       |    for dep in deps:
       |        if BspInfo not in dep:
       |            continue
       |        bsp = dep[BspInfo]
       |        if not hasattr(bsp, "output_groups") or bsp.output_groups == None:
       |            continue
       |        for k, v in bsp.output_groups.items():
       |            groups[k] = depset(transitive = [groups.get(k, depset()), v])
       |
       |def _update_output_group(groups, key, new_set):
       |    groups[key] = depset(transitive = [groups.get(key, depset()), new_set])
       |
       |# ---------- JVM info ----------
       |
       |def _get_jvm_provider(target):
       |    if hasattr(target, "scala"):
       |        return target.scala
       |    if JavaInfo in target:
       |        return target[JavaInfo]
       |    return None
       |
       |def _get_binary_jars(output):
       |    if hasattr(output, "class_jar") and output.class_jar:
       |        return [output.class_jar]
       |    return []
       |
       |def _get_interface_jars(output):
       |    if hasattr(output, "ijar") and output.ijar:
       |        return [output.ijar]
       |    return []
       |
       |def _get_source_jars(output):
       |    if hasattr(output, "source_jars"):
       |        sj = output.source_jars
       |        if type(sj) == "depset":
       |            return sj.to_list()
       |        return list(sj)
       |    if hasattr(output, "source_jar") and output.source_jar != None:
       |        return [output.source_jar]
       |    return []
       |
       |def _jvm_outputs_struct(output):
       |    return struct(
       |        binary_jars = _file_locs(_get_binary_jars(output)),
       |        interface_jars = _file_locs(_get_interface_jars(output)),
       |        source_jars = _file_locs(_get_source_jars(output)),
       |    )
       |
       |def _extract_jvm_info(target, ctx):
       |    provider = _get_jvm_provider(target)
       |    if not provider:
       |        return None
       |
       |    java_outputs = []
       |    if hasattr(provider, "java_outputs") and provider.java_outputs:
       |        java_outputs = provider.java_outputs
       |    elif hasattr(provider, "outputs") and provider.outputs:
       |        java_outputs = provider.outputs.jars
       |
       |    if not java_outputs:
       |        return None
       |
       |    jdeps_files = []
       |    if JavaInfo in target:
       |        jdeps_files = [jo.jdeps for jo in target[JavaInfo].java_outputs if jo.jdeps != None]
       |
       |    jars = [_jvm_outputs_struct(o) for o in java_outputs]
       |
       |    javac_opts = [opt for opt in getattr(ctx.rule.attr, "javacopts", [])]
       |    for export in getattr(ctx.rule.attr, "add_exports", []):
       |        javac_opts.append("--add-exports=" + export + "=ALL-UNNAMED")
       |    for open_pkg in getattr(ctx.rule.attr, "add_opens", []):
       |        javac_opts.append("--add-opens=" + open_pkg + "=ALL-UNNAMED")
       |
       |    tcj = []
       |    if hasattr(provider, "transitive_compile_time_jars"):
       |        tcj = provider.transitive_compile_time_jars.to_list()
       |
       |    return struct(
       |        jars = jars,
       |        generated_jars = [],
       |        javac_opts = javac_opts,
       |        jvm_flags = getattr(ctx.rule.attr, "jvm_flags", []),
       |        main_class = getattr(ctx.rule.attr, "main_class", ""),
       |        args = getattr(ctx.rule.attr, "args", []),
       |        jdeps = _file_locs(jdeps_files),
       |        transitive_compile_time_jars = _file_locs(tcj),
       |    )
       |
       |# ---------- Scala info ----------
       |
       |SCALA_TOOLCHAIN_TYPE = $scalaToolchainType
       |
       |SCALA_COMPILER_NAMES = [
       |    "scala3-compiler", "scala-compiler",
       |]
       |SCALA_LIBRARY_NAMES = [
       |    "scala3-interfaces", "scala3-library", "scala3-reflect",
       |    "scala-asm", "scala-library", "scala-reflect",
       |    "tasty-core", "compiler-interface",
       |]
       |
       |def _find_compiler_classpath(runfiles):
       |    result = []
       |    found_compiler = False
       |    for f in runfiles:
       |        if f.extension != "jar":
       |            continue
       |        name = f.basename
       |        is_compiler = False
       |        for cn in SCALA_COMPILER_NAMES:
       |            if cn in name:
       |                is_compiler = True
       |                break
       |        if is_compiler:
       |            found_compiler = True
       |            result.append(f)
       |            continue
       |        for ln in SCALA_LIBRARY_NAMES:
       |            if ln in name:
       |                result.append(f)
       |                break
       |    return result if found_compiler and len(result) >= 2 else []
       |
       |def _extract_scala_info(target, ctx):
       |    kind = ctx.rule.kind
       |    if not kind.startswith("scala_") and not kind.startswith("thrift_"):
       |        return None
       |
       |    rule_attr = ctx.rule.attr
       |    scalac_opts = list(getattr(rule_attr, "scalacopts", []))
       |
       |    if SCALA_TOOLCHAIN_TYPE != None and hasattr(rule_attr, "_scala_toolchain"):
       |        tc = ctx.toolchains[SCALA_TOOLCHAIN_TYPE]
       |        if tc != None and hasattr(tc, "scalacopts"):
       |            scalac_opts = list(tc.scalacopts) + scalac_opts
       |
       |    compiler_cp = []
       |    if hasattr(rule_attr, "_scalac"):
       |        scalac_target = rule_attr._scalac
       |        if scalac_target and hasattr(scalac_target, "default_runfiles"):
       |            compiler_cp = _find_compiler_classpath(
       |                scalac_target.default_runfiles.files.to_list(),
       |            )
       |
       |    scalatest_cp = []
       |    for attr_name in ["_scalatest", "_scalatest_runner", "_scalatest_reporter"]:
       |        attr_val = getattr(rule_attr, attr_name, None)
       |        if attr_val != None and JavaInfo in attr_val:
       |            scalatest_cp.extend(
       |                attr_val[JavaInfo].full_compile_jars.to_list(),
       |            )
       |
       |    return struct(
       |        scalac_opts = scalac_opts,
       |        compiler_classpath = _file_locs(compiler_cp),
       |        scalatest_classpath = _file_locs(scalatest_cp),
       |    )
       |
       |# ---------- Java toolchain / runtime ----------
       |
       |def _extract_java_toolchain(target, ctx, dep_targets):
       |    toolchain = None
       |    if hasattr(target, "java_toolchain"):
       |        toolchain = target.java_toolchain
       |    elif hasattr(java_common, "JavaToolchainInfo") and \\
       |         java_common.JavaToolchainInfo != platform_common.ToolchainInfo and \\
       |         java_common.JavaToolchainInfo in target:
       |        toolchain = target[java_common.JavaToolchainInfo]
       |
       |    if toolchain != None:
       |        java_home = None
       |        if hasattr(toolchain, "java_runtime") and hasattr(toolchain.java_runtime, "java_home"):
       |            java_home = _file_loc(toolchain.java_runtime.java_home) if type(toolchain.java_runtime.java_home) != "string" else struct(path = str(toolchain.java_runtime.java_home), short_path = str(toolchain.java_runtime.java_home), is_source = False)
       |        return struct(
       |            source_version = toolchain.source_version,
       |            target_version = toolchain.target_version,
       |            java_home = java_home,
       |        )
       |
       |    for dep in dep_targets:
       |        if BspInfo in dep and dep[BspInfo].java_toolchain_info != None:
       |            return dep[BspInfo].java_toolchain_info
       |    return None
       |
       |def _extract_java_runtime(target, ctx, dep_targets):
       |    runtime = None
       |    if hasattr(java_common, "JavaRuntimeInfo") and java_common.JavaRuntimeInfo in target:
       |        runtime = target[java_common.JavaRuntimeInfo]
       |
       |    if runtime != None and hasattr(runtime, "java_home"):
       |        jh = runtime.java_home
       |        return struct(
       |            java_home = _file_loc(jh) if type(jh) != "string" else struct(path = str(jh), short_path = str(jh), is_source = False),
       |        )
       |
       |    for dep in dep_targets:
       |        if BspInfo in dep and dep[BspInfo].java_runtime_info != None:
       |            return dep[BspInfo].java_runtime_info
       |    return None
       |
       |# ---------- Main aspect ----------
       |
       |def _bsp_target_info_aspect_impl(target, ctx):
       |    if target.label.name.endswith(".semanticdb"):
       |        return []
       |    if AnalysisTestResultInfo in target:
       |        return []
       |
       |    rule_attrs = ctx.rule.attr
       |
       |    compile_dep_targets = _collect_targets(rule_attrs, ["deps", "jars", "exports"])
       |    runtime_dep_targets = _collect_targets(rule_attrs, ["runtime_deps"])
       |    private_dep_targets = _collect_targets(rule_attrs, ["_java_toolchain", "_jvm", "runtime_jdk"])
       |
       |    compile_deps = [struct(id = str(t.label), dependency_type = COMPILE) for t in compile_dep_targets]
       |    runtime_deps = [struct(id = str(t.label), dependency_type = RUNTIME) for t in runtime_dep_targets]
       |    all_deps = compile_deps + runtime_deps
       |
       |    all_dep_targets = compile_dep_targets + runtime_dep_targets + private_dep_targets
       |
       |    output_groups = dict()
       |    _merge_output_groups(output_groups, all_dep_targets)
       |
       |    # Sources
       |    all_source_files = _files_from_attr(getattr(rule_attrs, "srcs", []))
       |    sources = [_file_loc(f) for f in all_source_files if f.is_source and not f.is_directory]
       |    generated_sources = [_file_loc(f) for f in all_source_files if not f.is_source and not f.is_directory]
       |
       |    # Resources
       |    resource_files = _files_from_attr(getattr(rule_attrs, "resources", []))
       |    resources = _file_locs(resource_files)
       |
       |    # Environment
       |    env = getattr(rule_attrs, "env", {})
       |    if type(env) == "Target":
       |        env = {}
       |    env_inherit = getattr(rule_attrs, "env_inherit", [])
       |
       |    # Executable
       |    default_info = target[DefaultInfo]
       |    executable = default_info and default_info.files_to_run.executable != None
       |
       |    # Sub-info
       |    jvm_info = _extract_jvm_info(target, ctx)
       |    scala_info = _extract_scala_info(target, ctx)
       |    jtc_info = _extract_java_toolchain(target, ctx, all_dep_targets)
       |    jrt_info = _extract_java_runtime(target, ctx, all_dep_targets)
       |
       |    info = dict(
       |        id = str(target.label),
       |        kind = ctx.rule.kind,
       |        tags = rule_attrs.tags,
       |        dependencies = all_deps,
       |        sources = sources,
       |        generated_sources = generated_sources,
       |        resources = resources,
       |        env = env,
       |        env_inherit = env_inherit,
       |        executable = executable,
       |    )
       |    if jvm_info != None:
       |        info["jvm_target_info"] = jvm_info
       |    if scala_info != None:
       |        info["scala_target_info"] = scala_info
       |    if jtc_info != None:
       |        info["java_toolchain_info"] = jtc_info
       |    if jrt_info != None:
       |        info["java_runtime_info"] = jrt_info
       |
       |    file_name = "bsp.%s-%s.bsp-info.json" % (target.label.name, _abs(hash(target.label.name)))
       |    info_file = ctx.actions.declare_file(file_name)
       |    ctx.actions.write(info_file, json.encode(struct(**info)))
       |    _update_output_group(output_groups, "bsp-target-info", depset([info_file]))
       |
       |    return [
       |        BspInfo(
       |            id = target.label,
       |            output_groups = output_groups,
       |            java_toolchain_info = jtc_info,
       |            java_runtime_info = jrt_info,
       |        ),
       |        OutputGroupInfo(**output_groups),
       |    ]
       |
       |_TOOLCHAINS = [SCALA_TOOLCHAIN_TYPE] if SCALA_TOOLCHAIN_TYPE != None else []
       |
       |bsp_target_info_aspect = aspect(
       |    implementation = _bsp_target_info_aspect_impl,
       |    attr_aspects = ["deps", "jars", "exports", "runtime_deps", "_java_toolchain", "_jvm", "runtime_jdk"],
       |    toolchains = _TOOLCHAINS,
       |)
       |""".stripMargin
  }
}
