name: Sourcegraph
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lsif:
    runs-on: ubuntu-latest
    name: "Upload LSIF"
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/setup-action@v1.1.1
      - run: cs install --contrib lsif-java
      - run: lsif-java index
      - name: src lsif upload
        run: |
          mkdir -p bin
          curl -L https://sourcegraph.com/.api/src-cli/src_linux_amd64 -o bin/src
          chmod +x bin/src
          ./bin/src lsif upload -github-token $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
