name: Sourcegraph
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  # Taken from gradle/gradle
  # On main, we don't want any jobs cancelled so the sha is used to name the group
  # On PR branches, we cancel the job if new commits are pushed
  group: ${{ (github.ref == 'refs/heads/main' ||  startsWith(github.ref, 'refs/tags') ) && format('sourcegraph-{0}', github.ref) || format('sourcegraph-pr-{0}', github.ref) }}
  cancel-in-progress: true
  
jobs:
  lsif:
    runs-on: ubuntu-latest
    name: "Upload SCIP"
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/setup-action@v1.2.1
      - run: cs launch --contrib scip-java -- index
      - name: src scip upload
        run: |
          mkdir -p bin
          curl -L https://sourcegraph.com/.api/src-cli/src_linux_amd64 -o bin/src
          chmod +x bin/src
          ./bin/src code-intel upload -trace=3 -ignore-upload-failure -github-token $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
