name: Test Failures Summary
run-name: "Test Failures Summary for ${{ github.event.workflow_run.pull_requests[0].number && format('PR #{0}', github.event.workflow_run.pull_requests[0].number) || format('commit {0}', github.event.workflow_run.head_sha) }}"

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  checks: write
  actions: read

jobs:
  aggregate-test-reports:
    name: Aggregate test reports
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts from triggering CI run
        uses: actions/download-artifact@v8
        with:
          path: artifacts
          merge-multiple: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Create the aggregated test report
        uses: dorny/test-reporter@9c978c66ab5564af606adee293b728670b2ca93c
        with:
          name: Aggregated test report
          path: "artifacts/**/target/test-reports/*.xml"
          reporter: java-junit
          list-suites: failed
          list-tests: failed
          list-files: failed
          use-actions-summary: false
          max-annotations: 0
