name: 'Test Failures Report'
on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
permissions:
  checks: write
  contents: read
  actions: read
jobs:
  aggregate-test-reports:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          persist-credentials: false
      - name: Download reports for each test job
        uses: dawidd6/action-download-artifact@v21
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: test-reports
          merge_multiple: true
      - name: Test Report
        uses: dorny/test-reporter@9c978c66ab5564af606adee293b728670b2ca93c
        with:
          name: Aggregated failure reports
          path: "**/target/test-reports/*.xml"
          reporter: java-junit
          list-suites: failed
          list-tests: failed
          list-files: failed
          use-actions-summary: false